AWSTemplateFormatVersion: '2010-09-09'
Description: Building Lambda with AWS SDK, CloudFormation and AWS CLI
Resources:
  MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/aws-sdk-iam-with-cf-cli
  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: aws-sdk-iam-with-cf-cli-lambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                Resource:
                  - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/aws-sdk-iam-with-cf-cli:*
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/aws-sdk-iam-with-cf-cli:*:*
              - Effect: Allow
                Action:
                  - iam:CreateUser
                  - iam:DeleteUser
                  - iam:ListUsers
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:user/*
      Path: /
      RoleName: aws-sdk-iam-with-cf-cli-us-east-1-lambdaRole
  LambdaFunctionWithCF:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: serverless-cookbook
        S3Key: iam-operations-0.0.1-SNAPSHOT.jar
      FunctionName: aws-sdk-iam-with-cf-cli
      Handler: tech.heartin.books.serverlesscookbook.MyLambdaHandler::handleRequest
      MemorySize: 512
      Role: !GetAtt IamRoleLambdaExecution.Arn
      Runtime: java8
      Timeout: 15
    DependsOn:
      - MyLogGroup
      - IamRoleLambdaExecution